app:
  port: "8080"
  host: "127.0.0.1"
  name: "lke_gateway"
  timezone: "Asia/Shanghai"
  language: "zh-CN"
  globalReqPathPrefix: "/reqPath"

databases:
  clientEnable: false
  masterDbName: "One of the following dbName"
  PDns: "仅在生产线上使用"
  EnableDbDynamicManage: true/false
  dbInfoList:
    - host: "host1"
      port: "port1"
      dbName: "dbName1"
      dbUser: "dbUser1"
      dbPass: "dbPass1"
    - host: "host2"
      port: "port2"
      dbName: "dbName2"
      dbUser: "dbUser2"
      dbPass: "dbPass2"

consul:
  addr: "192.168.0.103"
  port: 8500
  enableServRegister: true
  enableObtainService: true
  check:
    checkTimeout: "10s"
    checkInterval: "10s"
    invalidServiceLogoutTime: "20s"
  service:
    spec: "@every 11s"
    designatedServices:
      - serviceName: "serv1"
        loadBalanceMode: "rr"
      - serviceName: "serv2"
        loadBalanceMode: "ssi"

redis:
  connInfo: "127.0.0.1:6379"

detection:
  token: true
  tokenService: "serviceName"
  tokenCheckServiceApiUrl: "token_check_url"
  authentication: false
  authService: "serviceName"
  authCheckServiceApiUrl: "auth_check_url"

systemEnv:
  env: "dev"
